spring:
  #  elasticsearch:
  #    uris: https://192.168.56.10:9200
  application:
    name: simplemall-search
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
server:
  port: 12000