server:
  port: 40000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: simplemall-cart
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
    port: 6379
logging:
  level:
    com.fangw.simplemall: error
