spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://simplemall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://simplemall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://simplemall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://simplemall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: simplemall_search_route
          uri: lb://simplemall-search
          predicates:
            - Host=search.simplemall.com
        - id: simplemall_auth_route
          uri: lb://simplemall-auth-server
          predicates:
            - Host=auth.simplemall.com
        - id: simplemall_host_route
          uri: lb://simplemall-product
          predicates:
            - Host=simplemall.com, item.simplemall.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: simplemall-gateway
server:
  port: 88