server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  application:
    name: simplemall-auth-server
  redis:
    host: 192.168.56.10
    port: 6379
